name:                go-logout
version:             0.2.0.0
github:              "githubuser/go-logout"
license:             LGPLv3
author:              "JoshMayBalGitHub"
maintainer:          "JoshMayBalGitHub@gitlab.com"
copyright:           "2023 JoshMayBalGitHub"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitLab at https://gitlab.com/JoshMayBalGitHub/go-logout/-/blob/main/README.md

dependencies:
- base >= 4.7 && < 5
- gi-gtk == 3.0.*
- gi-gtk-hs
- haskell-gi-base
- process
- directory
- text

library:
  source-dirs: src

executables:
  go-logout-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - go-logout

tests:
  go-logout-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - go-logout
